### PR TITLE
apple-bundles: fix iOS framework signing

### PR DESCRIPTION
**Pull request by kabiroberai**
Submitted to this repo per https://github.com/indygreg/PyOxidizer/pull/640#issuecomment-1250393759.

### CODE REVIEW

**Review by indygreg — APPROVED** [review]
Thank you for the fix!

**Comment by kabiroberai** [comment]
fwiw you might wanna hold off on merging for a few minutes, adding a quick unit test for this

**Comment by kabiroberai** [comment]
@indygreg erm I probably should've run the existing tests too, because it looks like this breaks non-"shallow" frameworks. Mind reverting the merge so that I can patch those up?

**Comment by indygreg** [comment]
Yeah, I just noticed it broke tests too :/

I reverted it on `main` and reopened the PR for you.

When you fix this up, feel free to cherry-pick the changelog updates from 0617f8b782ba1deb06a6e667f749794e6f185ed9.

**Comment by dvc94ch** [comment]
can you elaborate on why you think signing frameworks doesn't work on ios? I've been signing flutter applications which include the flutter framework just fine.

**Comment by dvc94ch** [comment]
actually this looks like a regression. I made exactly the same change here: https://github.com/indygreg/PyOxidizer/compare/main...dvc94ch:PyOxidizer:nested-frameworks

**Comment by kabiroberai** [comment]
@dvc94ch iOS frameworks are structurally different from macOS frameworks, in that the only requirement is an `Info.plist` file inside the framework at the root level. While a macOS framework looks something like
```
Foo.framework/
  Resources/
    Info.plist
```
potentially with multiple nested versions, an iOS framework has the form
```
Foo.framework/
  Info.plist
```
This structure isn't correctly detected by apple-bundles, in turn leading to the framework being handled incorrectly in the CodeResources file. The unit tests that I add should hopefully illustrate the issue better.

**Comment by dvc94ch** [comment]
@indygreg rejected this change as incorrect https://github.com/indygreg/PyOxidizer/pull/539 I'm pretty sure he was right although I don't remember the reason. can you show me all the "code" you're using? I'll try to figure out what the correct solution was.

**Comment by kabiroberai** [comment]
I'm using this in a relatively large private project so unfortunately I can't share all the code atm, but you should be able to repro the issue by signing an iOS app with an embedded dynamic framework. I'll try to create a minimal reproducible example and share it here.

**Comment by dvc94ch** [comment]
can you try building with xbuild? if it builds with xbuild something else is wrong here: https://github.com/cloudpeers/xbuild

**Comment by kabiroberai** [comment]
Do you have a sample project I can test with xbuild? Also, is the Flutter framework dynamic or static?

**Comment by kabiroberai** [comment]
[SigningIssue.zip](https://github.com/indygreg/apple-platform-rs/files/9958334/SigningIssue.zip) here's a sample project that fails to be signed correctly (just Xcode's SwiftUI template with an empty dynamic framework added). To verify this for yourself, try:
```
xcodebuild CODE_SIGNING_ALLOWED=NO
rcodesign sign build/Release-iphoneos/SigningIssue.app
codesign -vvvv build/Release-iphoneos/SigningIssue.app
```

**Comment by kabiroberai** [comment]
looks like it's still signing incorrectly with my new changes (the old three-line diff was making it sign correctly, but it turns out it was erroneously identifying the .app as a `BundlePackageType::Framework`). Still working on modifying the new patch set to fix this, but it looks like there are indeed other bugs at play as well.

**Comment by dvc94ch** [comment]
what you're describing sounds awefully familiar.

**Comment by kabiroberai** [comment]
Ah it looks like the other necessary change is to prevent framework digests from being included in the CodeResources of iOS app bundles, i.e. changing this line
https://github.com/indygreg/apple-platform-rs/blob/63f916f8a79903107d0b0d153b1a57231a04d392/apple-codesign/src/bundle_signing.rs#L545
to
```rust
if !self.bundle.shallow() {
```

**Comment by kabiroberai** [comment]
This seems to line up with what other tools like ldid do as well: https://github.com/ProcursusTeam/ldid/blob/f0b3af5c0336acf97f87c7f8984771224c8b3483/ldid.cpp#L3194-L3200

**Review by dvc94ch — CHANGES_REQUESTED** [review]
need some time to complete my investigation. most likely culprit (having experienced exactly the same issue) is that the `rcodesign` cli doesn't use the correct settings on ios.

**Comment by kabiroberai** [comment]
Curious what you mean by "correct settings" — if you're referring to the fact that macOS and iOS have different base CodeResources rules then yeah I agree that's probably the root cause. Though the fact that iOS frameworks aren't recognized is definitely _one of_ the issues at play.

FWIW with 4577b8e in place things seem to be working correctly on both iOS and macOS, though I can't be 100% sure that we haven't missed an edge case. Additionally, there are likely other signing issues on iOS that we're missing, but this PR is an incremental step that at least fixes the simple case of an app with a nested dynamic framework.

**Comment by dvc94ch** [comment]
well, I might be completely wrong but some git digging showed this:
1. same fix was proposed
2. fix was rejected as being wrong
3. I managed to fix the issue in a different way
later you mentioned that the fix was actually wrong (erroneously identifying as a framework), I had the exact same thing. but I'm having a really hard time coming up with what the actual solution was.

the issue you're having is:
```
SigningIssue.app: a sealed resource is missing or invalid
file missing: SigningIssue.app/Frameworks/DummyLib.framework
```

and yes the flutter framework is a dynamic framework:
```
file Flutter.framework/Flutter
Flutter.framework/Flutter: Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|BINDS_TO_WEAK|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>
```

**Comment by dvc94ch** [comment]
well, I'm coming up empty. so if @indygreg thinks the changes make sense, they probably do.

**Review by indygreg — APPROVED** [review]
This looks good to me. The narrow scoping of the change should be low risk and fixes identification of iOS framework bundles.

As for why I rejected a similar change months ago, that's because bundle signing was completely broken at the time and the change didn't make sense in the context of _everything is broken_.

I'll patch this slightly locally to fix a merge conflict.

Thanks for the fix!

**Pull request closed without merging**
